name: build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup rust
        run: |
          rustup update stable

      - name: build
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --all-targets --all-features
          cargo build --release

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup coverage tools
        run: |
          rustup update stable
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov --locked

      - name: generate coverage
        run: |
          cargo llvm-cov --all-targets --all-features --lcov --output-path coverage.lcov

      - name: upload coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov
          format: lcov
